[package]
name = "bevy_bump"
version = "0.1.0"
edition = "2021"

[features]
default = ["enumset_layer"]
enumset_layer = ["enumset"]

[dependencies]
bevy = { version = "0.15", default-features = false }
iter-n = "0.1.0"
replace_with = "0.1.7"
enumset = { version = "1.1", optional = true }


